import {
  defineConfig,
  presetAttributify,
  presetUno,
  presetIcons,
  presetTypography,
  presetWebFonts,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss';
import { presetAnimations } from 'unocss-preset-animations';

export default defineConfig({
  presets: [
    presetAttributify(),
    presetUno(),
    presetIcons(),
    presetTypography(),
    presetAnimations({ fillMode: 'both' }),
    presetWebFonts({
      extendTheme: true,
      provider: 'bunny',
      fonts: {
        sans: 'Poppins:300,400,600',
        mono: 'Fira Mono:300,400,600',
        code: 'Fira Code:400,600',
      },
    }),
  ],
  transformers: [transformerDirectives(), transformerVariantGroup()],
  theme: {
    colors: {
      text: {
        50: 'rgb(var(--text-50) / %alpha)',
        100: 'rgb(var(--text-100) / %alpha)',
        200: 'rgb(var(--text-200) / %alpha)',
        300: 'rgb(var(--text-300) / %alpha)',
        400: 'rgb(var(--text-400) / %alpha)',
        500: 'rgb(var(--text-500) / %alpha)',
        600: 'rgb(var(--text-600) / %alpha)',
        700: 'rgb(var(--text-700) / %alpha)',
        800: 'rgb(var(--text-800) / %alpha)',
        900: 'rgb(var(--text-900) / %alpha)',
        950: 'rgb(var(--text-950) / %alpha)',
        default: 'rgb(var(--text) / %alpha)',
      },
      background: {
        50: 'rgb(var(--background-50) / %alpha)',
        100: 'rgb(var(--background-100) / %alpha)',
        200: 'rgb(var(--background-200) / %alpha)',
        300: 'rgb(var(--background-300) / %alpha)',
        400: 'rgb(var(--background-400) / %alpha)',
        500: 'rgb(var(--background-500) / %alpha)',
        600: 'rgb(var(--background-600) / %alpha)',
        700: 'rgb(var(--background-700) / %alpha)',
        800: 'rgb(var(--background-800) / %alpha)',
        900: 'rgb(var(--background-900) / %alpha)',
        950: 'rgb(var(--background-950) / %alpha)',
        default: 'rgb(var(--background) / %alpha)',
      },
      primary: {
        50: 'rgb(var(--primary-50) / %alpha)',
        100: 'rgb(var(--primary-100) / %alpha)',
        200: 'rgb(var(--primary-200) / %alpha)',
        300: 'rgb(var(--primary-300) / %alpha)',
        400: 'rgb(var(--primary-400) / %alpha)',
        500: 'rgb(var(--primary-500) / %alpha)',
        600: 'rgb(var(--primary-600) / %alpha)',
        700: 'rgb(var(--primary-700) / %alpha)',
        800: 'rgb(var(--primary-800) / %alpha)',
        900: 'rgb(var(--primary-900) / %alpha)',
        950: 'rgb(var(--primary-950) / %alpha)',
        default: 'rgb(var(--primary) / %alpha)',
      },
      secondary: {
        50: 'rgb(var(--secondary-50) / %alpha)',
        100: 'rgb(var(--secondary-100) / %alpha)',
        200: 'rgb(var(--secondary-200) / %alpha)',
        300: 'rgb(var(--secondary-300) / %alpha)',
        400: 'rgb(var(--secondary-400) / %alpha)',
        500: 'rgb(var(--secondary-500) / %alpha)',
        600: 'rgb(var(--secondary-600) / %alpha)',
        700: 'rgb(var(--secondary-700) / %alpha)',
        800: 'rgb(var(--secondary-800) / %alpha)',
        900: 'rgb(var(--secondary-900) / %alpha)',
        950: 'rgb(var(--secondary-950) / %alpha)',
        default: 'rgb(var(--secondary) / %alpha)',
      },
      accent: {
        50: 'rgb(var(--accent-50) / %alpha)',
        100: 'rgb(var(--accent-100) / %alpha)',
        200: 'rgb(var(--accent-200) / %alpha)',
        300: 'rgb(var(--accent-300) / %alpha)',
        400: 'rgb(var(--accent-400) / %alpha)',
        500: 'rgb(var(--accent-500) / %alpha)',
        600: 'rgb(var(--accent-600) / %alpha)',
        700: 'rgb(var(--accent-700) / %alpha)',
        800: 'rgb(var(--accent-800) / %alpha)',
        900: 'rgb(var(--accent-900) / %alpha)',
        950: 'rgb(var(--accent-950) / %alpha)',
        default: 'rgb(var(--accent) / %alpha)',
      },
    },
  },
});
